"""Rule-based negative control construction for the Study 2 judge validation gate.

docs/設計ブロック_0621.md §4 / CLAUDE.md #12: negative controls must be built
mechanically from the dataset's own fields, never free-generated by an LLM (LLM
free-generation would reintroduce the provenance circularity already avoided in
PersonaMem Phase A removal — see src/study1_mcq/phaseA_removal_feasibility.py).

Two rules are attempted in fixed priority order:
  r1 value substitution: deterministic regex match + fixed-offset substitution of
     one detectable atomic value (year / weekday / month / ordinal day / integer)
     in the gold answer, producing a fluent but evidence-unsupported response.
  r2 generic deflection: a fixed template that mechanically splices in the verbatim
     question text but states no committal, evidence-specific content.
If neither produces a response distinct from the positive control, the negative
control is recorded as unavailable — a feasibility finding, not an error (rules are
not loosened post hoc to force coverage; CLAUDE.md #12).
"""

import re

WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

_YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")
# Case-sensitive (exact capitalized form only): case-insensitive matching hits
# common English words that collide with month/weekday spelling, e.g. the modal
# verb "may" inside "may not prefer" matching the month "May". Gold date values
# in these answer strings are capitalized, so requiring exact capitalization
# avoids that false match without losing real date substitutions.
_WEEKDAY_RE = re.compile(r"\b(" + "|".join(WEEKDAYS) + r")\b")
_MONTH_RE = re.compile(r"\b(" + "|".join(MONTHS) + r")\b")
_ORDINAL_DAY_RE = re.compile(r"\b(\d{1,2})(st|nd|rd|th)\b")
_INTEGER_RE = re.compile(r"\b\d{1,3}\b")


def _ordinal_suffix(n: int) -> str:
    if 11 <= n % 100 <= 13:
        return "th"
    return {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")


def _substitute_value(text: str) -> str | None:
    """Try, in fixed priority order, to substitute one detectable atomic value.

    Returns the corrupted text, or None if no rule matched.
    """
    m = _YEAR_RE.search(text)
    if m:
        new_year = int(m.group()) + 1
        return text[: m.start()] + str(new_year) + text[m.end() :]

    m = _WEEKDAY_RE.search(text)
    if m:
        idx = WEEKDAYS.index(m.group())
        new_day = WEEKDAYS[(idx + 3) % 7]
        return text[: m.start()] + new_day + text[m.end() :]

    m = _MONTH_RE.search(text)
    if m:
        idx = MONTHS.index(m.group())
        new_month = MONTHS[(idx + 3) % 12]
        return text[: m.start()] + new_month + text[m.end() :]

    m = _ORDINAL_DAY_RE.search(text)
    if m:
        day = int(m.group(1))
        new_day = ((day - 1 + 2) % 28) + 1
        return text[: m.start()] + f"{new_day}{_ordinal_suffix(new_day)}" + text[m.end() :]

    m = _INTEGER_RE.search(text)
    if m:
        new_val = int(m.group()) + 2
        return text[: m.start()] + str(new_val) + text[m.end() :]

    return None


def _generic_deflection(question: str) -> str:
    return (
        "I don't have a specific detail confirmed for that — nothing definite "
        f"stands out to me regarding: {question}"
    )


def build_negative_control(question: str, positive_control_response: str) -> dict:
    """Build a rule-based negative control for one item.

    Returns dict with keys: negative_control_response, negative_control_rule
    ("r1"/"r2"/"unavailable"), negative_control_reason.
    """
    if not question or positive_control_response in (None, ""):
        return {
            "negative_control_response": "",
            "negative_control_rule": "unavailable",
            "negative_control_reason": "question or positive_control_response is empty",
        }
    positive_control_response = str(positive_control_response)

    r1_result = _substitute_value(positive_control_response)
    if r1_result is not None and r1_result != positive_control_response:
        return {
            "negative_control_response": r1_result,
            "negative_control_rule": "r1",
            "negative_control_reason": "value substitution on a detectable atomic value (year/weekday/month/day/integer)",
        }

    r2_result = _generic_deflection(question)
    if r2_result != positive_control_response:
        return {
            "negative_control_response": r2_result,
            "negative_control_rule": "r2",
            "negative_control_reason": "generic on-topic deflection template (no gold-specific content)",
        }

    return {
        "negative_control_response": "",
        "negative_control_rule": "unavailable",
        "negative_control_reason": "no rule produced a response distinct from positive_control_response",
    }
